// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJnU4bW48o1pL-Nj2CChVpd1jMyJTwn6w',
    appId: '1:297020514783:android:f59d677ba57436d2c9246a',
    messagingSenderId: '297020514783',
    projectId: 'cricplay-c5602',
    storageBucket: 'cricplay-c5602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg-mmLNa7EmWbR3tQvLWdDFihj3mQnpzI',
    appId: '1:297020514783:ios:8133edf3220823fac9246a',
    messagingSenderId: '297020514783',
    projectId: 'cricplay-c5602',
    storageBucket: 'cricplay-c5602.appspot.com',
    iosClientId: '297020514783-vqk4rbd1rh51c29k0dvbar0q80mp9not.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycricplay',
  );
}
